---
title: "Democratic Breakdown and Terrorism"
author: "Christopher Junk"
date: "7/23/2019"
output: ioslides_presentation

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE, messages = FALSE, wwarning = FALSE)
library(tidyverse)
```

```{r Load ESG and GTD data, cache=T, warning=F, message=F}
gtd_names <- read.csv('C:/Users/Christopher/Documents/Data/GTD_0718dist/gtd_all_1970-2017.csv') %>% 
  janitor::clean_names() %>% 
  dplyr::select(country_txt, country) %>% 
  group_by(country, country_txt) %>% 
  summarise()

terror <- read.csv('C:/Users/Christopher/Documents/Data/esg_dom.csv') %>% 
  janitor::clean_names() %>% 
  left_join(gtd_names)
```

```{r ESG to country-year UoA, cache=T, warning=F, message=F}
terror_count_year <- terror %>% 
  mutate(cowcode = countrycode::countrycode(country_txt, 
                                            origin = 'country.name', 
                                            destination = 'cown'),
         cowabb = countrycode::countrycode(country_txt, 
                                            origin = 'country.name', 
                                            destination = 'cowc'),
         attack = 1, 
         nwound = round(ifelse(nwound < 0, 
                         NA, 
                         nwound), 0), 
         nkill = round(ifelse(nkill < 0, 
                        NA, 
                        nkill), 0)) %>% 
  group_by(cowabb, cowcode, iyear) %>% 
  summarise(n_attack = sum(attack), 
            n_wound = sum(nwound, na.rm = T), 
            n_kill = sum(nkill, na.rm = T)) %>% 
  mutate(year = iyear)
```

```{r Create universe of possible cases, cache=T, warning=F, message=F}
states <- read.csv('http://www.correlatesofwar.org/data-sets/state-system-membership/states2016/at_download/file') %>% 
  mutate(duration = round(endyear - styear + 1, 0)) %>% 
  add_count(stateabb) %>% 
  group_by(ccode) %>% 
  mutate(seq = seq_along(ccode), 
         key = paste0(stateabb, seq)) %>% 
  uncount(duration, .remove = F) %>% 
  dplyr::select(cowabb = stateabb,
         cowcode = ccode,
         styear, endyear, n, duration, seq, key) %>% 
  ungroup() %>% 
  group_by(key) %>% 
  mutate(year_count = seq_along(key),
         year = styear + year_count - 1) %>% 
  filter(year >= 1970 & year <= 2007) %>% 
  ungroup() %>% 
  dplyr::select(cowcode, cowabb, year)
```

```{r Join country-year terrorism with system composition, cache=T, message=F, warning=F}
terror_country_year <- left_join(states, terror_count_year) %>% 
  filter(!is.na(cowcode)) %>% 
  mutate(n_attack = ifelse(is.na(n_attack), 
                           0, 
                           n_attack), 
         n_wound = ifelse(is.na(n_wound), 
                          0, 
                          n_wound), 
         n_kill = ifelse(is.na(n_kill), 
                         0,
                         n_kill), 
         casualties = n_wound + n_kill, 
         cas_rate = ifelse(n_attack == 0, 
                           0, 
                           casualties/n_attack)) %>% 
  dplyr::select(-iyear)
```

```{r Load VDEM data, cache=T, warning=F, message=F}
vdem <- read.csv('C:/Users/Christopher/Documents/Data/vdem/vdem/V-Dem-CY-Full+Others-v9.csv') %>% 
  janitor::clean_names()
```

```{r Select VDEM variables, cache=T, warning=F, message=F}
vdem_keep <- vdem %>% 
  dplyr::select(year, 
         cowcode = co_wcode, 
         gdp_pc_log10 = e_migdppcln, #log10 GDP per capita 
         pop = e_mipopula, #population
         dem_breakdown = e_democracy_breakdowns, #number of previous democratic breakdowns 
         elec_dem = v2x_polyarchy, #electoral democracy index
         lib_dem = v2x_libdem, #liberal democracy index 
         partic_dem = v2x_partipdem, #participation democracy index
         egal_dem = v2x_egaldem, #egalitarian democracy index
         free_express = v2x_freexp_altinf, #Freedom of expression and alternative sources of information index
         free_assoc = v2x_frassoc_thick, #freedom of association thick index 
         civ_soc_partic = v2x_cspart, #civil society participation index
         barrier_parties = v2psbars, #barriers to parties
         oppo_party_autonomy = v2psoppaut, #opposition parties autonomy
         free_ac_cult = v2clacfree, #freedom of academic and cultural expression
         free_relig = v2clrelig, #freedom of religion 
         social_class_eq = v2clacjust, #social class equality in respect for civil liberties 
         social_group_eq = v2clsocgrp, #social group equality in respect for civil liberties
         cso_enter_exit_reg = v2cseeorgs, #civil society organization entry and exit (high values mean no government regulation)
         cso_rep = v2csreprss, #civil society organization (CSO) repression 
         cso_antisys = v2csantimv, #CSO anti-system movements 
         relig_org_oppress = v2csrlgrep, #religios organization oppression 
         n_coup = e_coups, #number of successful coups in a year 
         gdp_grow = e_migdpgro, #GDP growth
         int_conflict = e_miinteco, #Country participated in armed international conflict (war, 1000 deaths)
         dom_conflict = e_miinterc, #experienced internal armed conflict 
         coup_desc = e_pt_coup, #0 no coup; 1 failed coup; 2 success coup 
         urbanization = e_miurbani, #urbanization (urban pop/pop)
         edu_avg = e_peaveduc, #average education years for 15+ YOs
         edu_gini = e_peedgini, #education gini 
         polity2 = e_polity2, #polity2 combnined score 
         resource_dist_equality = v2xeg_eqdr #equal distribution of resources
         ) %>% 
  filter(year >= 1970 & year <= 2007) %>% 
  mutate(weak_dem = ifelse(polity2 >= 1 & polity2 <= 6, 
                           1, 
                           0),
         democracy = ifelse(polity2 > 6, 
                            1, 
                            0),
         failed_coup = ifelse(coup_desc == 1, 
                              1, 
                              0)) %>% 
  dplyr::select(-coup_desc)

terror_vdem_country_year <- left_join(terror_country_year, vdem_keep) %>% 
  dplyr::select(-cowcode, -n_kill, -n_wound)
```

```{r AMELIA multiple imputation of missing VDEM values, cache = T, warning=F, message=F, include=F}
set.seed(7117)
ter_vdem_country_year_amelia <- Amelia::amelia(terror_vdem_country_year,
                                               m = 5,
                                               ts = "year",
                                               cs = "cowabb")
```

```{r ZINB number of attacks FULL SAMPLE, cache=T, include=F, warnings = F, message=F}

analysis_imp1 <- ter_vdem_country_year_amelia[1]$imputations[1] %>% data.frame %>% 
  janitor::clean_names() 

colnames(analysis_imp1) <- stringr::str_replace_all(colnames(analysis_imp1), 
                                                    "imp1_",
                                                    "")

mean_pop <- terror_vdem_country_year %>% 
  group_by(cowabb) %>% 
  summarise(mean_pop = mean(pop, na.rm = T))




zinb_full <- pscl::zeroinfl(n_attack ~ log10(abs(pop)+1) + gdp_pc_log10 + dem_breakdown + edu_avg + dom_conflict + int_conflict + civ_soc_partic + democracy + weak_dem | log10(pop) + gdp_pc_log10 + edu_avg + dom_conflict + int_conflict + democracy + weak_dem, 
                      data = analysis_imp1, 
                      dist = 'negbin')

zinb_full$coefficients$count
summary(zinb_full)
```

```{r ZINB predicted values, cache=T, include=F}
prediction_breakdowns <- analysis_imp1 %>% 
  summarise(pop = mean(log10(pop)))

```


```{r EBA, cache=T, warning=F, message=F, warning=F}
library(ExtremeBounds)
analysis_imp1 <- ter_vdem_country_year_amelia[1]$imputations[1] %>% data.frame %>% 
  janitor::clean_names() 

colnames(analysis_imp1) <- stringr::str_replace_all(colnames(analysis_imp1), 
                                                    "imp1_",
                                                    "")
analysis_imp1 <- analysis_imp1 %>% 
  mutate(ln_n_attack = log10(n_attack + .0000001))

free = c("pop", "gdp_pc_log10")
focus = c("dem_breakdown", "elec_dem", "lib_dem", "partic_dem", "egal_dem", "free_express", "free_assoc", "civ_soc_partic", "barrier_parties", "oppo_party_autonomy", "free_ac_cult", "free_relig", "social_class_eq", "social_group_eq", "cso_enter_exit_reg", "cso_rep", "cso_antisys", "relig_org_oppress", "n_coup", "gdp_grow", "int_conflict", "dom_conflict", "urbanization", "edu_avg", "edu_gini", "polity2", "resource_dist_equality", "weak_dem", "democracy", "failed_coup")

se.robust <- function(model.object) {
  model.fit <- sandwich::vcovHC(model.object, type = "HC")
  out <- sqrt(diag(model.fit))
  return(out)
}

eba <- eba(data = analysis_imp1, 
           y = "ln_n_attack", 
           free = free,
           focus = focus, 
           vif = 7, 
           weights = "adj.r.squared", 
           se.fun = se.robust)
```

## 

```{r EBA Coefplot, cache=T, message=F, warning=F, fig.dim = c(7.5, 5.5), fig.align='center'}
#Define labels for variables 
labels <- c(pop = "Population", 
              gdp_pc_log10 = "Logged GDP PC", 
              dem_breakdown = "Dem. Breakdowns", 
              elec_dem = "Elect. Dem.", 
              lib_dem = "Lib. Dem.", 
              partic_dem = "Partic. Dem", 
              egal_dem = "Egal. Dem.",
              free_express = "Free Expr.", 
              free_assoc = "Free Assoc.", 
              civ_soc_partic = "Civ. Soc. Partic.", 
              barrier_parties = "Pol. Party Barriers", 
              oppo_party_autonomy = "Oppo. Party Aut.", 
              free_ac_cult = "Free Ac./Cult. Expr.", 
              free_relig = "Relig. Free", 
              social_class_eq = "Class Eq.",
              social_group_eq = "Group Eq.",
              cso_enter_exit_reg = "Civ. Soc. Orgs.",
              cso_rep = "Civ. Soc. Repr.",
              cso_antisys = "Anti-System Civ. Soc.",
              relig_org_oppress = "Relig. Repr.",
              n_coup = "N Coups",
              gdp_grow = "GDP Growth",
              int_conflict = "Int. Conflict",
              dom_conflict = "Dom. Conflict",
              urbanization = "Urbanization",
              edu_avg = "15+ Edu. Avg.",
              edu_gini = "Edu. Ineq.",
              polity2 = "Polity 2",
              resource_dist_equality = "Resource Ineq.",
              weak_dem = "Weak Dem.",
              democracy = "Full Dem.",
              failed_coup = "Failed Coup")

eba_coef <- eba$regressions$beta %>% data.frame %>% dplyr::select(-X.Intercept.)

eba_coef_gather <- gather(eba_coef) %>%
  filter(!is.na(value))


ggplot(eba_coef_gather) + 
  geom_histogram(aes(value), 
                 bins = 40) +  
  geom_vline(xintercept = 0, 
             color = 'red') + 
  facet_wrap(. ~ key, 
             scales = 'free', 
             ncol = 7, 
             labeller = labeller(key = c(labels))) + 
  labs(title = "OLS EBA: All Coefficient Histograms") +
  theme(strip.background = element_blank(),
        strip.text = element_text(size = 6),
        axis.text = element_text(size = 5), 
        plot.title = element_text(size = 15),
        axis.title = element_blank())

```

## 

```{r EBA hist for only 95 significant variables, cache=T, include=T, fig.dim = c(7.5, 5.5), fig.align='center'}
eba_coef_gather %>% 
  filter(!is.na(value) & 
           key %in% c("pop", 
                   "dem_breakdown", 
                   "barrier_parties", 
                   "oppo_party_autonomy", 
                   "social_group_eq", 
                   "int_conflict",
                   "dom_conflict", 
                   "resource_dist_equality",
                   "weak_dem",
                   "polity2", 
                   "free_assoc")) %>% 
  ggplot() + 
  geom_histogram(aes(value), 
                 bins = 40) +  
  geom_vline(xintercept = 0, 
             color = 'red') + 
  facet_wrap(. ~ key, 
             scales = 'free', 
             ncol = 4, 
             labeller = labeller(key = c(labels))) + 
  labs(title = "OLS EBA: Notable Coefficient Histograms") +
  theme(strip.background = element_blank(),
        strip.text = element_text(),
        axis.text.x = element_text(size = 7), 
        plot.title = element_text(size = 15),
        axis.title = element_blank())
```

```{r EBA for casualty rate, include=F, cache=T}
eba_cas_rate <- eba(data = analysis_imp1, 
           y = "cas_rate", 
           free = free,
           focus = focus, 
           vif = 7, 
           weights = "adj.r.squared", 
           se.fun = se.robust)
```
